# Generated by Django 5.0.6 on 2024-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocompra',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=100),
        ),
    ]
