# Generated by Django 5.0.6 on 2024-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_estadocompra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcompra',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='estadocompra',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Cotización', 'Cotización'), ('Aprobado', 'Aprobado'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Cotización', 'Cotización'), ('Aprobado', 'Aprobado'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=100),
        ),
    ]
